# Generated by Django 5.2.8 on 2026-01-14 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الأكاديمية')),
                ('description', models.TextField(blank=True, help_text='نبذة مختصرة تظهر في الصفحة الرئيسية', null=True, verbose_name='وصف الأكاديمية')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='academy_logos/', verbose_name='شعار الأكاديمية')),
            ],
            options={
                'verbose_name': 'أكاديمية',
                'verbose_name_plural': 'الأكاديميات',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدولة')),
                ('currency', models.CharField(max_length=10, verbose_name='العملة (EGP, USD)')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السنة (مثال: الصف الأول الثانوي)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.country', verbose_name='تابع لدولة')),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الكورس')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_months', models.IntegerField(default=1, verbose_name='مدة الكورس (بالأشهر)')),
                ('sessions_count', models.IntegerField(default=8, verbose_name='عدد الحصص في الكورس')),
                ('payment_type', models.CharField(choices=[('monthly', 'دفع شهري'), ('full', 'دفع كامل (مرة واحدة)')], default='monthly', max_length=20, verbose_name='نظام الدفع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الكورس')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear', verbose_name='السنة الدراسية')),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.academy', verbose_name='الأكاديمية')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.country')),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'الكورسات',
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع التعليم')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_types', to='core.country', verbose_name='تابع لدولة')),
            ],
            options={
                'verbose_name': 'نوع تعليم',
                'verbose_name_plural': 'أنواع التعليم',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بدء الاشتراك')),
                ('is_completed', models.BooleanField(default=False, verbose_name='منتهي')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='الكورس')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المدير')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'مدير إداري',
                'verbose_name_plural': 'المديرون الإداريون',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='نص الرسالة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستقبل')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الطالب')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('parent_name', models.CharField(max_length=150, verbose_name='اسم ولي الأمر')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='رقم هاتف ولي الأمر')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='ايميل ولي الأمر')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear', verbose_name='السنة الدراسية')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='الدولة')),
                ('courses', models.ManyToManyField(through='core.Enrollment', to='core.course', verbose_name='الكورسات المسجلة')),
                ('education_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.educationtype', verbose_name='نوع التعليم')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='الطالب'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='الدولة')),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.educationtype', verbose_name='نوع التعليم')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='المادة الدراسية'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المشرف')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'مشرف',
                'verbose_name_plural': 'المشرفون',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.supervisor', verbose_name='المشرف المسؤول'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المعلم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة عن المعلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(related_name='teachers', to='core.subject', verbose_name='المواد التي يدرسها')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='core.teacher'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='المعلم المختار'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف (اختياري)')),
                ('file', models.FileField(upload_to='materials/%Y/%m/', verbose_name='الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.course', verbose_name='الكورس')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'مادة علمية',
                'verbose_name_plural': 'المكتبة والمواد',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الحصة')),
                ('status', models.CharField(choices=[('present', 'حضور'), ('absent', 'غياب')], default='present', max_length=10, verbose_name='الحالة')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.enrollment', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'سجل حصة',
                'verbose_name_plural': 'سجلات الحضور والغياب',
                'unique_together': {('enrollment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى التقرير')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='daily_reports/', verbose_name='ملف مرفق')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرفع')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='core.student', verbose_name='الطالب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='core.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'تقرير يومي',
                'verbose_name_plural': 'التقارير اليومية',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'teacher', 'date')},
            },
        ),
    ]
