# Generated by Django 5.2.8 on 2026-01-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
    ]
