# Generated by Django 5.2.8 on 2026-01-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='course',
            name='academic_years',
            field=models.ManyToManyField(blank=True, to='core.academicyear', verbose_name='السنوات الدراسية'),
        ),
    ]
