# Generated by Django 6.0.3 on 2026-05-20 13:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicalacademicyear_historicalacademy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('default_role', models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], max_length=20, null=True, verbose_name='الدور الافتراضي')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'historical ملف مستخدم موحد',
                'verbose_name_plural': 'historical ملفات المستخدمين الموحدة',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_role', models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], max_length=20, null=True, verbose_name='الدور الافتراضي')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unified_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم موحد',
                'verbose_name_plural': 'ملفات المستخدمين الموحدة',
            },
        ),
    ]
