# Generated by Django 6.0.3 on 2026-05-20 13:22

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('core', 'UserProfile')
    
    for user in User.objects.all():
        # Get or create UserProfile
        profile, created = UserProfile.objects.get_or_create(user=user)
        
        # Determine default role based on existing profiles
        if hasattr(user, 'manager_profile') or user.is_superuser:
            profile.default_role = 'manager'
        elif hasattr(user, 'supervisor_profile'):
            profile.default_role = 'supervisor'
        elif hasattr(user, 'teacher_profile'):
            profile.default_role = 'teacher'
        elif hasattr(user, 'student_profile'):
            profile.default_role = 'student'
        
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicaluserprofile_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
