# Generated by Django 5.2.8 on 2026-01-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('tf', 'صح أو خطأ')], default='mcq', max_length=10, verbose_name='نوع السؤال')),
                ('marks', models.PositiveIntegerField(default=1, verbose_name='الدرجة')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='نص الاختيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة؟')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
            options={
                'verbose_name': 'اختيار',
                'verbose_name_plural': 'الاختيارات',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('description', models.TextField(blank=True, verbose_name='وصف الاختبار')),
                ('duration', models.PositiveIntegerField(help_text='المدة بالدقائق', verbose_name='مدة الاختبار')),
                ('pass_score', models.PositiveIntegerField(default=50, help_text='النسبة المئوية للنجاح (مثلاً 50)', verbose_name='درجة النجاح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.course', verbose_name='الكورس')),
                ('specific_students', models.ManyToManyField(blank=True, related_name='private_quizzes', to='core.student', verbose_name='تخصيص لطلاب محددين (اختياري)')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='الدرجة المحققة')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح؟')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاختبار')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.student')),
            ],
            options={
                'verbose_name': 'نتيجة اختبار',
                'verbose_name_plural': 'نتائج الاختبارات',
            },
        ),
    ]
