# Generated by Django 6.0.3 on 2026-05-25 16:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_historicalchoice_historicalquestion_historicalquiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquiz',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الحصة'),
        ),
        migrations.AddField(
            model_name='historicalquizattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('graded', 'تم التصحيح')], default='graded', max_length=20, verbose_name='حالة التصحيح'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الحصة'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('graded', 'تم التصحيح')], default='graded', max_length=20, verbose_name='حالة التصحيح'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('tf', 'صح أو خطأ'), ('essay', 'سؤال مقالي')], default='mcq', max_length=10, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('tf', 'صح أو خطأ'), ('essay', 'سؤال مقالي')], default='mcq', max_length=10, verbose_name='نوع السؤال'),
        ),
        migrations.CreateModel(
            name='HistoricalStudentAnswer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('essay_answer', models.TextField(blank=True, null=True, verbose_name='الإجابة المقالية')),
                ('marks_earned', models.FloatField(default=0.0, verbose_name='الدرجة المستحقة')),
                ('is_graded', models.BooleanField(default=False, verbose_name='تم تصحيحه؟')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attempt', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quiz.quizattempt', verbose_name='محاولة الاختبار')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quiz.question', verbose_name='السؤال')),
                ('selected_choice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quiz.choice', verbose_name='الخيار المختار')),
            ],
            options={
                'verbose_name': 'historical إجابة الطالب',
                'verbose_name_plural': 'historical إجابات الطلاب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_answer', models.TextField(blank=True, null=True, verbose_name='الإجابة المقالية')),
                ('marks_earned', models.FloatField(default=0.0, verbose_name='الدرجة المستحقة')),
                ('is_graded', models.BooleanField(default=False, verbose_name='تم تصحيحه؟')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='محاولة الاختبار')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='السؤال')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name='الخيار المختار')),
            ],
            options={
                'verbose_name': 'إجابة الطالب',
                'verbose_name_plural': 'إجابات الطلاب',
            },
        ),
    ]
