"""
Django settings for academy_project project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os
from dotenv import load_dotenv
from django.templatetags.static import static

# تحميل متغيرات البيئة من ملف .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Security Settings ---
# SECURITY WARNING: keep the secret key used in production secret!
# جلب المفتاح من البيئة، أو استخدام مفتاح مؤقت للتطوير فقط في حال عدم وجوده
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-dev-key-change-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
# تحويل القيمة النصية إلى Boolean
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# جلب الهوستات المسموحة وفصلها بفاصلة
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# --- Application Definition ---

INSTALLED_APPS = [
    # Unfold Admin Interface
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",

    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My Apps
    'core',
    'sslserver',
    'quiz',
    'simple_history',
    'django_filters',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.RoleContextMiddleware',
    'core.middleware.RoleAccessMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.MediaCacheMiddleware',
]

ROOT_URLCONF = 'academy_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.unfold_dashboard', # Unfold Dashboard KPI
                'core.context_processors.nav_items',
            ],
        },
    },
]

WSGI_APPLICATION = 'academy_project.wsgi.application'


# --- Database ---
if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- Internationalization ---
LANGUAGE_CODE = 'ar-eg'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True


# --- Static & Media Files ---
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# WhiteNoise Cache Settings
WHITENOISE_MAX_AGE = 31536000  # 1 year


# إعدادات الوسائط (للمرفقات والصور)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- Default Primary Key ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Auth Redirects ---
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/login/' # Fallback; custom logic handles redirection based on role.
LOGOUT_REDIRECT_URL = '/admin/'


# --- Email Configuration (Gmail SMTP) ---
# هذه الإعدادات لإرسال إيميلات حقيقية

# --- Celery and Redis Configuration ---
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Run tasks synchronously in development if Redis/Celery is offline or by default
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', str(DEBUG)).lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# جلب بيانات الإيميل الحساسة من متغيرات البيئة
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') 

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# --- Unfold Admin Theme Settings ---
UNFOLD = {
    "SITE_TITLE": "VexaLearn Admin",
    "SITE_HEADER": "VexaLearn",
    "SITE_URL": "/",
    # "SITE_ICON": {
    #     "light": lambda request: static("admin/img/logo-light.svg"),  # يمكنك وضع مسار شعارك هنا
    #     "dark": lambda request: static("admin/img/logo-dark.svg"),
    # },
    
    # --- 1. إعدادات القائمة الجانبية (Sidebar) ---
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("لوحة التحكم"),
                "separator": True,
                "items": [
                    {
                        "title": _("الرئيسية"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("إدارة المستخدمين"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("الطلاب"),
                        "icon": "face",
                        "link": reverse_lazy("admin:core_student_changelist"),
                    },
                    {
                        "title": _("المعلمون"),
                        "icon": "school",
                        "link": reverse_lazy("admin:core_teacher_changelist"),
                    },
                    {
                        "title": _("المشرفون"),
                        "icon": "supervisor_account",
                        "link": reverse_lazy("admin:core_supervisor_changelist"),
                    },
                    {
                        "title": _("المديرون"),
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:core_manager_changelist"),
                    },
                     {
                        "title": _("حسابات النظام"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": _("المحتوى التعليمي"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("الأكاديميات"),
                        "icon": "domain",
                        "link": reverse_lazy("admin:core_academy_changelist"),
                    },
                    {
                        "title": _("الكورسات"),
                        "icon": "class",
                        "link": reverse_lazy("admin:core_course_changelist"),
                    },
                    {
                        "title": _("المواد الدراسية"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:core_subject_changelist"),
                    },
                    {
                        "title": _("مكتبة الملفات"),
                        "icon": "folder_shared",
                        "link": reverse_lazy("admin:core_coursematerial_changelist"),
                    },
                ],
            },
            {
                "title": _("الاشتراكات والعمليات"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("الاشتراكات"),
                        "icon": "card_membership",
                        "link": reverse_lazy("admin:core_enrollment_changelist"),
                    },
                    {
                        "title": _("سجلات الحضور"),
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:core_attendance_changelist"),
                    },
                    {
                        "title": _("التقارير اليومية"),
                        "icon": "assessment",
                        "link": reverse_lazy("admin:core_dailyreport_changelist"),
                    },
                ],
            },
            {
                "title": _("تواصل النظام"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("الرسائل (Chat)"),
                        "icon": "chat",
                        "link": reverse_lazy("admin:core_message_changelist"),
                    },
                    {
                        "title": _("الإشعارات"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:core_notification_changelist"),
                    },
                ],
            },
            {
                "title": _("بيانات النظام الأساسية"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("الدول"),
                        "icon": "public",
                        "link": reverse_lazy("admin:core_country_changelist"),
                    },
                    {
                        "title": _("أنواع التعليم"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:core_educationtype_changelist"),
                    },
                    {
                        "title": _("السنوات الدراسية"),
                        "icon": "calendar_today",
                        "link": reverse_lazy("admin:core_academicyear_changelist"),
                    },
                ],
            },
            {
                "title": _("سجل المراجعة (Audit)"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("سجل الطلاب"),
                        "icon": "history",
                        "link": reverse_lazy("admin:core_historicalstudent_changelist"),
                    },
                    {
                        "title": _("سجل المعلمين"),
                        "icon": "history",
                        "link": reverse_lazy("admin:core_historicalteacher_changelist"),
                    },
                    {
                        "title": _("سجل الاشتراكات"),
                        "icon": "history",
                        "link": reverse_lazy("admin:core_historicalenrollment_changelist"),
                    },
                ],
            },
        ],
    },

    # --- 2. تحسينات النصوص والألوان ---
    "COLORS": {
        "primary": {
            "50": "245 243 255",
            "100": "237 233 254",
            "200": "221 214 254",
            "300": "196 181 253",
            "400": "167 139 250",
            "500": "139 92 246",
            "600": "124 58 237",
            "700": "109 40 217",
            "800": "91 33 182",
            "900": "76 29 149",
            "950": "46 16 101",
        },
    },
}

AGORA_APP_ID = os.environ.get('AGORA_APP_ID')
AGORA_APP_CERTIFICATE = os.environ.get('AGORA_APP_CERTIFICATE')

CSRF_TRUSTED_ORIGINS = ['https://vexalearn.cloud', 'https://www.vexalearn.cloud']

# تفعيل أمان الكوكيز (لأنك تستخدم HTTPS)
SECURE_SSL_REDIRECT = False  # اتركها False لأن Cloudflare/Nginx يقوم بالتحويل غالباً
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
