<<<<<<< HEAD
"""
Django settings for academy_project project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os
from dotenv import load_dotenv
from django.templatetags.static import static

# تحميل متغيرات البيئة من ملف .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Security Settings ---
# SECURITY WARNING: keep the secret key used in production secret!
# جلب المفتاح من البيئة، أو استخدام مفتاح مؤقت للتطوير فقط في حال عدم وجوده
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-dev-key-change-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
# تحويل القيمة النصية إلى Boolean
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# جلب الهوستات المسموحة وفصلها بفاصلة
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# --- Application Definition ---

INSTALLED_APPS = [
    # Unfold Admin Interface
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",

    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My Apps
    'core',
    'sslserver',
    'quiz',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'academy_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.unfold_dashboard', # Unfold Dashboard KPI
            ],
        },
    },
]

WSGI_APPLICATION = 'academy_project.wsgi.application'


# --- Database ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- Internationalization ---
LANGUAGE_CODE = 'ar-eg'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True


# --- Static & Media Files ---
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# إعدادات الوسائط (للمرفقات والصور)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- Default Primary Key ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Auth Redirects ---
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/admin/'


# --- Email Configuration (Gmail SMTP) ---
# هذه الإعدادات لإرسال إيميلات حقيقية
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# جلب بيانات الإيميل الحساسة من متغيرات البيئة
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') 

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# --- Unfold Admin Theme Settings ---
UNFOLD = {
    "SITE_TITLE": "VexaLearn Admin",
    "SITE_HEADER": "VexaLearn",
    "SITE_URL": "/",
    # "SITE_ICON": {
    #     "light": lambda request: static("admin/img/logo-light.svg"),  # يمكنك وضع مسار شعارك هنا
    #     "dark": lambda request: static("admin/img/logo-dark.svg"),
    # },
    
    # --- 1. إعدادات القائمة الجانبية (Sidebar) ---
    "SIDEBAR": {
        "show_search": True,  # إظهار شريط البحث في القائمة
        "show_all_applications": False, # إخفاء التطبيقات غير المخصصة لترتيب القائمة يدوياً
        "navigation": [
            {
                "title": _("إدارة المستخدمين"),
                "separator": True,  # خط فاصل
                "collapsible": True, # قابل للطي لتوفير مساحة
                "items": [
                    {
                        "title": _("المديرون"),
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:core_manager_changelist"),
                    },
                    {
                        "title": _("المشرفون"),
                        "icon": "supervisor_account",
                        "link": reverse_lazy("admin:core_supervisor_changelist"),
                    },
                    {
                        "title": _("المعلمون"),
                        "icon": "school",
                        "link": reverse_lazy("admin:core_teacher_changelist"),
                    },
                    {
                        "title": _("الطلاب"),
                        "icon": "face",
                        "link": reverse_lazy("admin:core_student_changelist"),
                    },
                     {
                        "title": _("المستخدمين (Users)"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": _("الهيكل الأكاديمي"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("الأكاديميات"),
                        "icon": "domain",
                        "link": reverse_lazy("admin:core_academy_changelist"),
                    },
                    {
                        "title": _("الدول"),
                        "icon": "public",
                        "link": reverse_lazy("admin:core_country_changelist"),
                    },
                    {
                        "title": _("أنواع التعليم"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:core_educationtype_changelist"),
                    },
                    {
                        "title": _("السنوات الدراسية"),
                        "icon": "calendar_today",
                        "link": reverse_lazy("admin:core_academicyear_changelist"),
                    },
                    {
                        "title": _("المواد الدراسية"),
                        "icon": "menu_book",  # أيقونة الكتاب
                        "link": reverse_lazy("admin:core_subject_changelist"),
                    },
                    {
                        "title": _("الكورسات"),
                        "icon": "class",
                        "link": reverse_lazy("admin:core_course_changelist"),
                    },
                ],
            },
            {
                "title": _("العمليات والاشتراكات"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("الاشتراكات"),
                        "icon": "card_membership",
                        "link": reverse_lazy("admin:core_enrollment_changelist"),
                    },
                    {
                        "title": _("سجلات الحضور"),
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:core_attendance_changelist"),
                    },
                ],
            },
            {
                "title": _("التواصل والمحتوى"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("مكتبة المواد"),
                        "icon": "folder_shared",
                        "link": reverse_lazy("admin:core_coursematerial_changelist"),
                    },
                    {
                        "title": _("الرسائل (Chat)"),
                        "icon": "chat",
                        "link": reverse_lazy("admin:core_message_changelist"),
                    },
                    {
                        "title": _("التقارير اليومية"),
                        "icon": "assessment",
                        "link": reverse_lazy("admin:core_dailyreport_changelist"),
                    },
                    {
                        "title": _("الإشعارات"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:core_notification_changelist"),
                    },
                ],
            },
        ],
    },

    # --- 2. تحسينات النصوص والألوان ---
    "COLORS": {
        "primary": {
            "50": "238 242 255",
            "100": "224 231 255",
            "200": "199 210 254",
            "300": "165 180 252",
            "400": "129 140 248",
            "500": "99 102 241",
            "600": "79 70 229",
            "700": "67 56 202",
            "800": "55 48 163",
            "900": "49 46 129",
            "950": "30 27 75",
        },
    },
}

AGORA_APP_ID = os.environ.get('AGORA_APP_ID')
AGORA_APP_CERTIFICATE = os.environ.get('AGORA_APP_CERTIFICATE')

CSRF_TRUSTED_ORIGINS = ['https://vexalearn.cloud', 'https://www.vexalearn.cloud']

# تفعيل أمان الكوكيز (لأنك تستخدم HTTPS)
SECURE_SSL_REDIRECT = False  # اتركها False لأن Cloudflare/Nginx يقوم بالتحويل غالباً
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
=======
"""
Django settings for academy_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t%mis!tb)csz2xbfxaztxk-9dtp!ca*n64r*(rcvyxrv!g=2t-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",  
    "unfold.contrib.forms",    
    "unfold.contrib.import_export",  

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # تطبيقاتي
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'academy_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # نتركها فارغة لأننا نستخدم مجلد templates داخل التطبيق core
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academy_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'  # اللغة العربية

TIME_ZONE = 'Africa/Cairo'  # توقيت القاهرة

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- إعدادات تسجيل الدخول والخروج ---
# بعد تسجيل الدخول بنجاح، يذهب المشرف إلى لوحة التحكم
LOGIN_REDIRECT_URL = '/dashboard/'

# بعد تسجيل الخروج، يعود المستخدم إلى صفحة تسجيل الدخول
LOGOUT_REDIRECT_URL = '/login/'






# إعدادات الواجهة العصرية (Unfold)
UNFOLD = {
    "SITE_TITLE": "أكاديمية المستقبل",
    "SITE_HEADER": "لوحة الإدارة",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",

    "STYLES": [
        lambda request: request.build_absolute_uri('/static/css/admin_fix.css'),
    ],
    # ألوان الموقع الرئيسية (يمكنك تغيير الكود السداسي للون الذي تحبه)
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",   # اللون البنفسجي العصري كمثال
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
        },
    },
    # القائمة الجانبية (Sidebar)
    "SIDEBAR": {
        "show_search": True,  # إظهار خانة بحث في القائمة
        "show_all_applications": True,
        "navigation": [
            {
                "title": "إدارة الأكاديمية",
                "separator": True,  # خط فاصل
                "items": [
                    {
                        "title": "الطلاب",
                        "icon": "school",  # أيقونة مدرسة
                        "link": reverse_lazy("admin:core_student_changelist"),
                    },
                    {
                        "title": "المعلمون",
                        "icon": "person_play", # أيقونة معلم
                        "link": reverse_lazy("admin:core_teacher_changelist"),
                    },
                     {
                        "title": "المشرفون",
                        "icon": "security", # أيقونة أمن
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
        ],
    },
}


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_USER = 'admin@academy.com'


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# عدد ثواني التخزين في المتصفح (صفر = لا تخزن)
CACHE_MIDDLEWARE_SECONDS = 0
>>>>>>> d5830918c0c5f5125220644ff97bb92f7726c7f7
